

#=========================================================================
# 
# Define / setting of ranking value
#
#=========================================================================

SPECIAL_BOOST: 100
PREF: 50000

# Title of notice
TITLE_PERFECT_MATCH: 10000
TITLE_PARTIAL_MATCH: 2000
TITLE_PARTIAL_MATCH_OFFSET_1: 500
TITLE_PARTIAL_MATCH_OFFSET_SUP: 300

# Creator of notice
CREATOR_PERFECT_MATCH: 5000
CREATOR_PARTIAL_MATCH: 1000
CREATOR_PARTIAL_MATCH_OFFSET_1: 300
CREATOR_PARTIAL_MATCH_OFFSET_SUP: 75

# Subject of notice
SUBJECT_PERFECT_MATCH: 5000
SUBJECT_PARTIAL_MATCH_OFFSET_1: 300
SUBJECT_PARTIAL_MATCH_OFFSET_SUP: 75

# Theme of notice
THEME_PERFECT_MATCH: 5000
THEME_PARTIAL_MATCH: 2000

#
INDICE_PERFECT_MATCH: 5000
INDICE_PARTIAL_MATCH: 2000
INDICE_PARTIAL_MATCH_OFFSET_1: 500
INDICE_PARTIAL_MATCH_OFFSET_SUP: 300

#
MAT_TYPE_MATCH: 5000
